// Supplier name mapping for logo files
export const SUPPLIER_LOGO_MAPPING: Record<string, string> = {
  'BOSCH': 'BOSCH.jpg',
  'VALEO': 'VALEO.jpg',
  'CONTINENTAL': 'CONTINENTAL.jpg',
  'MAHLE': 'MAHLE.jpg',
  'MANN FILTER': 'MFILTRE.jpg',
  'MANN-FILTER': 'MFILTRE.jpg',
  'MANNFILTER': 'MFILTRE.jpg',
  'FRAM': 'FRAP.jpg',
  'CASTROL': 'CASTROL.jpg',
  'MOTUL': 'MOTUL.jpg',
  'TOTAL': 'TOTAL.jpg',
  'ELF': 'ELF.jpg',
  'SHELL': 'SHELL.jpg',
  'LIQUI MOLY': 'LIQUI_MOLY.jpg',
  'LIQUI-MOLY': 'LIQUI_MOLY.jpg',
  'NGK': 'NGK.jpg',
  'DENSO': 'DENSO.jpg',
  'CHAMPION': 'CHAMPION.jpg',
  'BERU': 'BERU.jpg',
  'FEBI BILSTEIN': 'FEBI_BILSTEIN.jpg',
  'FEBI-BILSTEIN': 'FEBI_BILSTEIN.jpg',
  'FEBIBILSTEIN': 'FEBI_BILSTEIN.jpg',
  'SACHS': 'SACHS.jpg',
  'LUK': 'LUK.jpg',
  'VICTOR REINZ': 'VICTOR_REINZ.jpg',
  'VICTOR-REINZ': 'VICTOR_REINZ.jpg',
  'VICTORREINZ': 'VICTOR_REINZ.jpg',
  'GATES': 'GATES.jpg',
  'DAYCO': 'DAYCO.jpg',
  'CONTITECH': 'CONTITECH.jpg',
  'MONROE': 'MONROE.jpg',
  'BILSTEIN': 'BILSTEIN.jpg',
  'KYB': 'KYB.jpg',
  'TRW': 'TRW.jpg',
  'DELPHI': 'DELPHI.jpg',
  'BREMBO': 'BREMBO.jpg',
  'ZEN': 'ZEN.jpg',
  'HELLA': 'HELLA.jpg',
  'OSRAM': 'OSRAM.jpg',
  'PHILIPS': 'PHILIPS.jpg',
  'VARTA': 'VARTA.jpg',
  'BOSCH': 'BOSCH.jpg',
  'EXIDE': 'EXIDE.jpg',
  'YUASA': 'YUASA.jpg',
  'RENAULT': 'RENAULT.jpg',
  'PEUGEOT': 'PEUGEOT.jpg',
  'CITROEN': 'CITROEN.jpg',
  'TOYOTA': 'TOYOTA.jpg',
  'NISSAN': 'NISSAN.jpg',
  'HONDA': 'HONDA.jpg',
  'HYUNDAI': 'HYUNDAI.jpg',
  'KIA': 'KIA.jpg',
  'MERCEDES': 'Mercedes.jpg',
  'MERCEDES-BENZ': 'Mercedes.jpg',
  'BMW': 'BMW.jpg',
  'AUDI': 'AUDI.jpg',
  'VOLKSWAGEN': 'VW_GROUP.jpg',
  'VW': 'VW_GROUP.jpg',
  'SEAT': 'VW_GROUP.jpg',
  'SKODA': 'VW_GROUP.jpg',
  'FIAT': 'FIAT.jpg',
  'ALFA ROMEO': 'ALFA_ROMEO.jpg',
  'LANCIA': 'LANCIA.jpg',
  'FORD': 'FORD.jpg',
  'OPEL': 'OPEL.jpg',
  'VAUXHALL': 'VAUXHALL.jpg',
  'JAGUAR': 'JAGUAR.jpg',
  'LAND ROVER': 'LAND_ROVER.jpg',
  'MINI': 'MINI.jpg',
  'SMART': 'SMART.jpg',
  'VOLVO': 'VOLVO.jpg',
  'SAAB': 'SAAB.jpg',
  'SUBARU': 'SUBARU.jpg',
  'MAZDA': 'MAZDA.jpg',
  'MITSUBISHI': 'MITSUBISHI.jpg',
  'SUZUKI': 'SUZUKI.jpg',
  'ISUZU': 'ISUZU.jpg',
  'DAIHATSU': 'DAIHATSU.jpg',
  'LEXUS': 'LEXUS.jpg',
  'INFINITI': 'INFINITI.jpg',
  'ACURA': 'ACURA.jpg',
  'GENESIS': 'GENESIS.jpg',
  'DS': 'DS.jpg',
  'DACIA': 'DACIA.jpg',
  'LADA': 'LADA.jpg',
  'UAZ': 'UAZ.jpg',
  'GAZ': 'GAZ.jpg',
  'ZAZ': 'ZAZ.jpg',
  'TATA': 'TATA.jpg',
  'MAHINDRA': 'MAHINDRA.jpg',
  'MARUTI': 'MARUTI.jpg',
  'BAJAJ': 'BAJAJ.jpg',
  'TVS': 'TVS.jpg',
  'HERO': 'HERO.jpg',
  'YAMAHA': 'YAMAHA.jpg',
  'KAWASAKI': 'KAWASAKI.jpg',
  'DUCATI': 'DUCATI.jpg',
  'KTM': 'KTM.jpg',
  'HUSQVARNA': 'HUSQVARNA.jpg',
  'APRILIA': 'APRILIA.jpg',
  'MOTO GUZZI': 'MOTO_GUZZI.jpg',
  'VESPA': 'VESPA.jpg',
  'PIAGGIO': 'PIAGGIO.jpg',
  'GILERA': 'GILERA.jpg',
  'DERBI': 'DERBI.jpg',
  'GAS GAS': 'GAS_GAS.jpg',
  'SHERCO': 'SHERCO.jpg',
  'BETA': 'BETA.jpg',
  'TM': 'TM.jpg',
  'HUSABERG': 'HUSABERG.jpg',
  'GASGAS': 'GASGAS.jpg',
  'RIEJU': 'RIEJU.jpg',
  'MONTESA': 'MONTESA.jpg',
  'BULTACO': 'BULTACO.jpg',
  'OSSA': 'OSSA.jpg',
  'DERBI': 'DERBI.jpg',
  'GAS GAS': 'GAS_GAS.jpg',
  'SHERCO': 'SHERCO.jpg',
  'BETA': 'BETA.jpg',
  'TM': 'TM.jpg',
  'HUSABERG': 'HUSABERG.jpg',
  'GASGAS': 'GASGAS.jpg',
  'RIEJU': 'RIEJU.jpg',
  'MONTESA': 'MONTESA.jpg',
  'BULTACO': 'BULTACO.jpg',
  'OSSA': 'OSSA.jpg',
}

export function getSupplierLogoFilename(supplierName: string): string {
  const normalizedName = supplierName.toUpperCase().trim()
  
  // Check direct mapping first
  if (SUPPLIER_LOGO_MAPPING[normalizedName]) {
    return SUPPLIER_LOGO_MAPPING[normalizedName]
  }
  
  // Try to find partial matches
  for (const [key, filename] of Object.entries(SUPPLIER_LOGO_MAPPING)) {
    if (normalizedName.includes(key) || key.includes(normalizedName)) {
      return filename
    }
  }
  
  // Fallback: clean the name and try common extensions
  const cleanName = normalizedName
    .replace(/[^A-Z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
  
  return `${cleanName}.jpg`
}
